* agent.nu

An agent harness written in nushell against the ollama api

** Agent strategy

If an MoE model can activate 17b parameters per expert and get decent performance can smaller models be fine tuned (or not) and used across time to the same effect?

A hieracrchical team of LLMs. A high-level leader who delegates to specific leaders. Specific leaders prepare delegation prompts for specific workers. Specific workers
may prepare prompts for specific tool callers.

Orchestration code that manages context for the team and batches requests to maximize throughput.

** Tools

*** High Level Leader's Toolbox

This agent keeps basically nothing in context. It sends work out to others like a "web-researcher" or "engineering-leader", gets responses back from them
and then delegates more work out. It's context is controlled primarily by the user.

- Delegate
  - Needs to supply an enum of delegatees
  - Which model runs for a delegate will come from the config file
  - Which persona a a delegate uses will come from the config file


*** Code Researcher's Toolbox

This agent searches on the filesystem for code relevant to some request.

- File Search
- Summarize Contents
  - Delegates to another agent
