* agent.nu

An agent harness written in nushell against the ollama api

If an MoE model can activate 17b parameters per expert and get decent performance can smaller models be fine tuned (or not) and used across time to the same effect?

A hieracrchical team of LLMs. A high-level leader who delegates to specific leaders. Specific leaders prepare delegation prompts for specific workers. Specific workers
may prepare prompts for specific tool callers.

Orchestration code that manages context for the team and batches requests to maximize throughput.

** Config

TODO: describe config interface

** Personas

TODO: describe personas interface

** Tools

TODO: describe tools interface

** TODO

- Fix the history worker setup so agents are resumable
  - Means the history needs to know some extra details (or a better storage structure needs to exist...)
  - Make a new dir for each time `agent.nu` is started
    - In it make a dir for each persona
    - Copy in the person.json (it'll have temp and stuff later, but has at least model now)
    - Start a new time based json(l?) for each persona started
  - Resume by specifying a json(l?) file

- Make tools have a pre-flight check, if they fail then don't add them to persona details? Or maybe just fail to start.
- Tools
  - write-file
- Target a CoreWars bot. I want to see it make a warrior that beats some of the current winners. Or past winners. Idk.    
- Context management commands
  - /clear
  - /context-remove-latest-response
  - /context-remove-latest-prompt
- Tools
  - find-files    
  - find-in-file
  - find-files-containing
  - replace-in-file
  - patch
    - maybe? I wonder if models are smart enough to make diff patches... hmm maybe if I give it diff...
  - diff
  - lsp?
  - bash?
  - calc?
- Track context usage
  - Would be best to know the model's context limits (or maybe set them...)
- Tool timeouts
- Prompt should handle navigation keys
- Save context and history separately
  - Context should be saved so that the session is /resumable/
  - History should be saved for analysis/review
- Manager starts history worker
- Resumable sessions
- Streaming response
